
/*****************************************************
** AUTOMATICALLY CREATED HTML LOADING CONFIGURATION **
*****************************************************/

// Please, do not edit this file. It is automatically generated by 'build.mutua.ts' task on every build with information present in 'mutua.instance-project.config.ts' and 'mutua.available.modules.and.components.config.ts'

// Included by 'web.modules.ts' to load the needed components and modules and make them available to the application

// components
/////////////

import { NG2AppComponent } from '../../shared/modules/m-ng2-admin/ng2app.component';
import { HomeComponent } from '../../components/pages/home/home.component';

export const MutuaExportedComponents: any[] = [NG2AppComponent,HomeComponent];

// routes
/////////

import { HomeRoutes } from '../../components/pages/home/home.routes';

export const MutuaExportedRoutes: any[] = [...HomeRoutes];

// modules
//////////

// MNg2AdminModule
import { MNg2AdminModule } from '../modules/m-ng2-admin/m-ng2-admin.module';
// BrowserAnimationsModule
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
// NgbModule
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
// MPRJModule
import { MPRJModule } from '../modules/m-mprj/m-mprj.module';

export const MutuaExportedModules: any[] = [MNg2AdminModule.forRoot(),BrowserAnimationsModule,NgbModule.forRoot(),MPRJModule.forRoot()];

export const MutuaAppComponent: any = NG2AppComponent;
