
/*******************************************************
** AUTOMATICALLY CREATED MOBILE LOADING CONFIGURATION **
*******************************************************/

// Please, do not edit this file. It is automatically generated by 'build.mutua.ts' task on every build with information present in 'mutua.instance-project.config.ts' and 'mutua.available.modules.and.components.config.ts'

// Included by 'nativescript/.../components.modules.ts' to load the needed components and modules and make them available to the application

// components
/////////////

import { AppComponent } from '../../components/app.component';
import { MPEdificandoOControleInternoHomeComponent } from '../../components/pages/mp-edificando-o-controle-interno-home/mp-edificando-o-controle-interno-home.component';
import { MPFaleComOMPRJComponent } from '../../components/pages/mp-fale-com-o-mprj/mp-fale-com-o-mprj.component';
import { MPInformacoesGeraisComponent } from '../../components/pages/mp-informacoes-gerais/mp-informacoes-gerais.component';
import { MPMetodologiaComponent } from '../../components/pages/mp-metodologia/mp-metodologia.component';
import { MPOutrosRankingsComponent } from '../../components/pages/mp-outros-rankings/mp-outros-rankings.component';
import { MPRankingCompletoComponent } from '../../components/pages/mp-ranking-completo/mp-ranking-completo.component';

export const MutuaExportedComponents: any[] = [AppComponent,MPEdificandoOControleInternoHomeComponent,MPFaleComOMPRJComponent,MPInformacoesGeraisComponent,MPMetodologiaComponent,MPOutrosRankingsComponent,MPRankingCompletoComponent];

// routes
/////////

import { MPEdificandoOControleInternoHomeRoutes } from '../../components/pages/mp-edificando-o-controle-interno-home/mp-edificando-o-controle-interno-home.routes';
import { MPFaleComOMPRJRoutes } from '../../components/pages/mp-fale-com-o-mprj/mp-fale-com-o-mprj.routes';
import { MPInformacoesGeraisRoutes } from '../../components/pages/mp-informacoes-gerais/mp-informacoes-gerais.routes';
import { MPMetodologiaRoutes } from '../../components/pages/mp-metodologia/mp-metodologia.routes';
import { MPOutrosRankingsRoutes } from '../../components/pages/mp-outros-rankings/mp-outros-rankings.routes';
import { MPRankingCompletoRoutes } from '../../components/pages/mp-ranking-completo/mp-ranking-completo.routes';

export const MutuaExportedRoutes: any[] = [...MPEdificandoOControleInternoHomeRoutes,...MPFaleComOMPRJRoutes,...MPInformacoesGeraisRoutes,...MPMetodologiaRoutes,...MPOutrosRankingsRoutes,...MPRankingCompletoRoutes];

// modules
//////////

// MHelloWorldModule
import { MHelloWorldModule } from '../modules/m-hello-world/m-hello-world.module';
// MEdificandoOControleInternoModule
import { MEdificandoOControleInternoModule } from '../modules/m-edificando-o-controle-interno/m-edificando-o-controle-interno.module';

export const MutuaExportedModules: any[] = [MHelloWorldModule.forRoot(),MEdificandoOControleInternoModule.forRoot()];

export const MutuaAppComponent: any = AppComponent;
