
/*******************************************************
** AUTOMATICALLY CREATED MOBILE LOADING CONFIGURATION **
*******************************************************/

// Please, do not edit this file. It is automatically generated by 'build.mutua.ts' task on every build with information present in 'mutua.instance-project.config.ts' and 'mutua.available.modules.and.components.config.ts'

// Included by 'nativescript/.../components.modules.ts' to load the needed components and modules and make them available to the application

// components
/////////////

import { AppComponent } from '../../components/app.component';
import { AboutComponent } from '../../components/about/about.component';
import { HomeComponent } from '../../components/home/home.component';
import { GvHomeComponent } from '../../components/pages/gv-home/gv-home.component';

export const MutuaExportedComponents: any[] = [AppComponent,AboutComponent,HomeComponent,GvHomeComponent];

// routes
/////////

import { AboutRoutes } from '../../components/about/about.routes';
import { HomeRoutes } from '../../components/home/home.routes';
import { GvHomeRoutes } from '../../components/pages/gv-home/gv-home.routes';

export const MutuaExportedRoutes: any[] = [...AboutRoutes,...HomeRoutes,...GvHomeRoutes];

// modules
//////////

// MHelloWorldModule
import { MHelloWorldModule } from '../modules/m-hello-world/m-hello-world.module';

export const MutuaExportedModules: any[] = [MHelloWorldModule.forRoot()];

export const MutuaAppComponent: any = AppComponent;
