
/*******************************************************
** AUTOMATICALLY CREATED MOBILE LOADING CONFIGURATION **
*******************************************************/

// Please, do not edit this file. It is automatically generated by 'build.mutua.ts' task on every build with information present in 'mutua.instance-project.config.ts' and 'mutua.available.modules.and.components.config.ts'

// Included by 'nativescript/.../components.modules.ts' to load the needed components and modules and make them available to the application

// components
/////////////

import { MPHomeComponent } from '../../components/pages/mp-home/mp-home.component';

export const MutuaExportedComponents: any[] = [MPHomeComponent];

// routes
/////////

import { MPHomeRoutes } from '../../components/pages/mp-home/mp-home.routes';

export const MutuaExportedRoutes: any[] = [...MPHomeRoutes];

// modules
//////////

// MPRJModule
import { MPRJModule } from '../modules/m-mprj/m-mprj.module';

export const MutuaExportedModules: any[] = [MPRJModule.forRoot()];

export const MutuaAppComponent: any = AppComponent;
